language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4.1

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors

script: python myLib.py
